# Create and Publish repository Packages

name: Publish Packages for Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Publish Release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Check Build
        run: ./gradlew assemble --warn
        timeout-minutes: 6

      - name: Generate JavaDoc
        run: ./gradlew javadoc --warn
        if: success()
        timeout-minutes: 3

      - name: Publish Packages
        run: ./gradlew publish --warn
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JavaDoc and Markdown
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: MT-JavaDocs
          path: /home/runner/work/*/*/*/build/dokka/
          retention-days: 60
        timeout-minutes: 2
